### ISSUE TITLE
Doesn't work when installed as a package dependency

### ISSUE THREAD

**Issue by nick-woodward** [ekristen/dns-proxy#30]
When adding `dns-proxy` as a package dependency and trying to run it using a npm script. 

```js
  // ...
  "scripts": {
    "start": "dns-proxy"
  },
  "dependencies": {
    "dns-proxy": "*"
    // ...
  }
  // ...
```

It will try to load `../dns-proxy.js` which doesn't exist relative to the bin that node runs.

### Workaround

```js
  // ...
  "scripts": {
    "start": "node node_modules/dns-proxy"
  }
  // ...
```

**Comment by ekristen** [comment]
Thanks to email alerts I totally missed these details when i was looking at this from my phone, sorry about that. I'll admit I never planned on this being used as a dependency. Let me take a look at the PR. 

Off the top of my head you could always do this now and have it work `node node_modules/dns-proxy/dns-proxy.js`

**Comment by nick-woodward** [comment]
That's actually what my workaround does except node reads the main property in the package.json on our behalf.

Also you've definitely created a rockstar module. This is so simple to setup compared to the alternatives.

**Comment by ekristen** [comment]
Thanks for the kind words, glad it works for you. I'm working on an update that will dynamically read in changes from the conf file.
