### ISSUE TITLE
ERR_SOCKET_CANNOT_SEND

### ISSUE THREAD

**Issue by jonwilts** [ekristen/dns-proxy#53]
Hey - don't know if you're still actively maintaining this. I have it running on my home network as my router doesn't allow me to add DNS entries for local machines, and it works (almost*) perfectly. So thank you.

Almost*: Running on Ubuntu 18.04.5. Every so often in syslog I see the following:

Sep 14 14:52:49 server1 dns-proxy[7015]: 2020-09-14T18:52:49.197Z dnsproxy:error Socket Error: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
Sep 14 14:52:49 server1 systemd[1]: dns-proxy.service: Main process exited, code=exited, status=5/NOTINSTALLED
Sep 14 14:52:49 server1 systemd[1]: dns-proxy.service: Failed with result 'exit-code'.
Sep 14 14:52:50 server1 systemd[1]: dns-proxy.service: Service hold-off time over, scheduling restart.
Sep 14 14:52:50 server1 systemd[1]: dns-proxy.service: Scheduled restart job, restart counter is at 31.
Sep 14 14:52:50 server1 systemd[1]: Stopped Local DNS proxy.
Sep 14 14:52:50 server1 systemd[1]: Started Local DNS proxy.
Sep 14 14:52:50 server1 dns-proxy[12011]: 2020-09-14T18:52:50.544Z dnsproxy:info we are up and listening at 192.168.77.2 on 53

It's not really a problem - the server restarts and runs fine - but maybe worth investigating. Happens probably 3 times a day. 

Thanks.

**Comment by jonwilts** [comment]
Following up, got a different error today, which may be related:

Sep 15 14:47:29 server1 dns-proxy[12011]: 2020-09-15T18:47:29.092Z dnsproxy:error Socket Error: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
Sep 15 14:47:29 server1 systemd[1]: dns-proxy.service: Main process exited, code=exited, status=5/NOTINSTALLED
Sep 15 14:47:29 server1 systemd[1]: dns-proxy.service: Failed with result 'exit-code'.
Sep 15 14:47:30 server1 systemd[1]: dns-proxy.service: Service hold-off time over, scheduling restart.
Sep 15 14:47:30 server1 systemd[1]: dns-proxy.service: Scheduled restart job, restart counter is at 32.
Sep 15 14:47:30 server1 systemd[1]: Stopped Local DNS proxy.
Sep 15 14:47:30 server1 systemd[1]: Started Local DNS proxy.
Sep 15 14:47:30 server1 dns-proxy[8366]: 2020-09-15T18:47:30.556Z dnsproxy:info we are up and listening at 192.168.77.2 on 53
Sep 15 14:48:30 server1 dns-proxy[8366]: /snapshot/dns-proxy/node_modules/native-dns-packet/packet.js:70
Sep 15 14:48:30 server1 dns-proxy[8366]:   len = buff.readUInt8();
Sep 15 14:48:30 server1 dns-proxy[8366]:              ^
Sep 15 14:48:30 server1 dns-proxy[8366]: VError: BufferCursorOverflow: length 12, position 12, size 1
Sep 15 14:48:30 server1 dns-proxy[8366]:     at module.exports.BufferCursor._checkWrite (/snapshot/dns-proxy/node_modules/buffercursor/buffercursor.js:0:0)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at module.exports.BufferCursor._move (/snapshot/dns-proxy/node_modules/buffercursor/buffercursor.js:0:0)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at module.exports.BufferCursor.readUInt8 (/snapshot/dns-proxy/node_modules/buffercursor/buffercursor.js:0:0)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at nameUnpack (/snapshot/dns-proxy/node_modules/native-dns-packet/packet.js:70:14)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at parseQuestion (/snapshot/dns-proxy/node_modules/native-dns-packet/packet.js:525:14)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at Function.Packet.parse (/snapshot/dns-proxy/node_modules/native-dns-packet/packet.js:704:17)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at Object.module.exports.listAnswer (/snapshot/dns-proxy/util.js:0:0)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at Socket.<anonymous> (/snapshot/dns-proxy/dns-proxy.js:0:0)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at emitTwo (events.js:126:13)
Sep 15 14:48:30 server1 dns-proxy[8366]:     at Socket.emit (events.js:214:7)
Sep 15 14:48:30 server1 systemd[1]: dns-proxy.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 14:48:30 server1 systemd[1]: dns-proxy.service: Failed with result 'exit-code'.
Sep 15 14:48:31 server1 systemd[1]: dns-proxy.service: Service hold-off time over, scheduling restart.
Sep 15 14:48:31 server1 systemd[1]: dns-proxy.service: Scheduled restart job, restart counter is at 33.
Sep 15 14:48:31 server1 systemd[1]: Stopped Local DNS proxy.
Sep 15 14:48:31 server1 systemd[1]: Started Local DNS proxy.
Sep 15 14:48:31 server1 dns-proxy[8440]: 2020-09-15T18:48:31.481Z dnsproxy:info we are up and listening at 192.168.77.2 on 53
Sep 15 14:50:26 server1 dns-proxy[8440]: 2020-09-15T18:50:26.929Z dnsproxy:error Socket Error: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
Sep 15 14:50:26 server1 systemd[1]: dns-proxy.service: Main process exited, code=exited, status=5/NOTINSTALLED
Sep 15 14:50:26 server1 systemd[1]: dns-proxy.service: Failed with result 'exit-code'.
Sep 15 14:50:28 server1 systemd[1]: dns-proxy.service: Service hold-off time over, scheduling restart.
Sep 15 14:50:28 server1 systemd[1]: dns-proxy.service: Scheduled restart job, restart counter is at 34.
Sep 15 14:50:28 server1 systemd[1]: Stopped Local DNS proxy.
Sep 15 14:50:28 server1 systemd[1]: Started Local DNS proxy.
Sep 15 14:50:28 server1 dns-proxy[8565]: 2020-09-15T18:50:28.231Z dnsproxy:info we are up and listening at 192.168.77.2 on 53
Sep 15 14:52:30 server1 dns-proxy[8565]: 2020-09-15T18:52:30.000Z dnsproxy:error Socket Error: Error [ERR_SOCKET_CANNOT_SEND]: Unable to send data
Sep 15 14:52:30 server1 systemd[1]: dns-proxy.service: Main process exited, code=exited, status=5/NOTINSTALLED
Sep 15 14:52:30 server1 systemd[1]: dns-proxy.service: Failed with result 'exit-code'.
Sep 15 14:52:31 server1 systemd[1]: dns-proxy.service: Service hold-off time over, scheduling restart.
Sep 15 14:52:31 server1 systemd[1]: dns-proxy.service: Scheduled restart job, restart counter is at 35.
Sep 15 14:52:31 server1 systemd[1]: Stopped Local DNS proxy.
Sep 15 14:52:31 server1 systemd[1]: Started Local DNS proxy.
Sep 15 14:52:31 server1 dns-proxy[8697]: 2020-09-15T18:52:31.231Z dnsproxy:info we are up and listening at 192.168.77.2 on 53

**Comment by ekristen** [comment]
Interesting. Could your IP be changing? Possibly try listening on 0.0.0.0 or 127.0.0.1 instead? The ERR_SOCKET_CANNOT_SEND error simply means it is unable to send data. It's unclear why.

**Comment by jonwilts** [comment]
Hey - thanks for getting back to me. IP is static so definitely not that, but I'll try listening on those and see if it helps. 

I'm running the binaries downloaded from github - I guess there's not a lot I can do to add more debug around this?

**Comment by jonwilts** [comment]
Quick follow up: I've been running dns-proxy on 0.0.0.0 now for 3 days and the problem hasn't reoccurred. Thanks for the help.

**Comment by ekristen** [comment]
Good deal.
